/**
 * Deterministic demo workspace used for portfolio screenshots.
 *
 *   pnpm --filter @phiguard/web seed:demo
 *
 * Unlike `dev-seed.ts` — which creates the minimum needed to log in — this
 * builds a clinic that has been running for months: three locations, all five
 * RBAC roles, work in every state, incidents mid-triage, a partly-completed
 * compliance program, and a real audit trail.
 *
 * Every value is generated by `@faker-js/faker` under a fixed seed, so runs are
 * reproducible and no real person's data can end up in a screenshot. Nothing
 * here is or resembles PHI: the records describe clinic operations and
 * workforce compliance, never patients.
 *
 * Mutations go through the domain libraries (`createTask`, `createIncident`,
 * `transitionIncident`, `completeItem`, ...) rather than raw inserts wherever
 * the library supports the end state. That is deliberate: those helpers write
 * audit events, so the seeded audit log is genuine rather than fabricated.
 */
import { faker } from '@faker-js/faker'
import { hashPassword } from 'better-auth/crypto'
import { getStandardLegalDocuments, hashDocument } from '@phiguard/baa'
import { auditEvents, withAuditContext } from '@phiguard/audit'
import {
  accessReviews,
  accounts,
  getDb,
  legalAcceptances,
  locationGrants,
  locations,
  memberships,
  organizations,
  soc2Evidence,
  users,
  type DB,
} from '@phiguard/db/server'
import { createTask, updateTaskStatus, assignTask, addComment } from '@phiguard/db/tasks'
import {
  acknowledgePolicy,
  assignChecklistTemplateToLocations,
  completeItem,
  createIncident,
  createPolicy,
  createRiskAssessment,
  createRiskItem,
  createTrainingCourse,
  createVendor,
  assignCourse,
  markCompleted,
  publishPolicy,
  recordBaa,
  recordManualEvidence,
  runSeed,
  seedSoc2Controls,
  openAccessReview,
  transitionIncident,
  checklistItems,
  checklists,
} from '@phiguard/compliance'
import { and, count, eq, inArray } from 'drizzle-orm'

// ── determinism ─────────────────────────────────────────────────────────────

// Chosen so the generated roster reads as an ordinary clinic staff list. Names
// come from `firstName`/`lastName` rather than `fullName` to avoid honorifics
// and suffixes, which look wrong in a members table.
const FAKER_SEED = 20260101
const DEMO_PASSWORD = 'DemoPassword123!'
const DEMO_ORG_SLUG = 'riverbend-health-partners'
const DEMO_ORG_NAME = 'Riverbend Health Partners'
const DEMO_EMAIL_DOMAIN = 'demo.phiguard.dev'

const STARTER_TEMPLATES = {
  accessReview: '11111111-1111-4111-8111-111111111111',
  riskCadence: '22222222-2222-4222-8222-222222222222',
  baaInventory: '33333333-3333-4333-8333-333333333333',
  trainingLog: '44444444-4444-4444-8444-444444444444',
} as const

const DAY_MS = 24 * 60 * 60 * 1000
const now = new Date()
const daysFromNow = (days: number) => new Date(now.getTime() + days * DAY_MS)
const daysAgo = (days: number) => daysFromNow(-days)

// ── shapes ──────────────────────────────────────────────────────────────────

type DemoRole = 'org_owner' | 'org_admin' | 'location_manager' | 'location_staff' | 'auditor'

type DemoPerson = {
  key: string
  email: string
  name: string
  role: DemoRole
  title: string
  /** Indexes into the location list; only meaningful for location-scoped roles. */
  locationIndexes: number[]
}

const LOCATION_DEFINITIONS = [
  { name: 'Riverbend Family Medicine', slug: 'riverbend-family', isPrimary: true },
  { name: 'Northgate Pediatrics', slug: 'northgate-pediatrics', isPrimary: false },
  { name: 'Lakeside Dermatology', slug: 'lakeside-dermatology', isPrimary: false },
]

const PEOPLE: Omit<DemoPerson, 'name'>[] = [
  { key: 'owner', email: `owner@${DEMO_EMAIL_DOMAIN}`, role: 'org_owner', title: 'Practice Administrator', locationIndexes: [0, 1, 2] },
  { key: 'admin', email: `admin@${DEMO_EMAIL_DOMAIN}`, role: 'org_admin', title: 'Compliance Officer', locationIndexes: [0, 1, 2] },
  { key: 'manager', email: `manager@${DEMO_EMAIL_DOMAIN}`, role: 'location_manager', title: 'Office Manager', locationIndexes: [1] },
  { key: 'staff', email: `staff@${DEMO_EMAIL_DOMAIN}`, role: 'location_staff', title: 'Front Desk Lead', locationIndexes: [1] },
  { key: 'auditor', email: `auditor@${DEMO_EMAIL_DOMAIN}`, role: 'auditor', title: 'External Auditor', locationIndexes: [0, 1, 2] },
]

/**
 * Task templates. `offsetDays` is relative to today: negatives are overdue, so
 * the list view shows its overdue treatment without depending on wall-clock.
 */
const TASK_TEMPLATES: {
  title: string
  description: string
  status: 'open' | 'in_progress' | 'blocked' | 'done'
  priority: 'low' | 'medium' | 'high' | 'urgent'
  offsetDays: number
  locationIndex: number
  assignee: string | null
}[] = [
  { title: 'Quarterly workforce access review', description: 'Confirm every active account still needs its current role. Record the decision for each member.', status: 'in_progress', priority: 'high', offsetDays: 4, locationIndex: 0, assignee: 'admin' },
  { title: 'Renew BAA with transcription vendor', description: 'Current agreement lapses next quarter. Route the countersigned copy into the vendor register.', status: 'open', priority: 'urgent', offsetDays: -3, locationIndex: 0, assignee: 'owner' },
  { title: 'Re-run annual HIPAA training for new hires', description: 'Four staff joined since the last cycle and have no completion on file.', status: 'open', priority: 'high', offsetDays: 11, locationIndex: 1, assignee: 'manager' },
  { title: 'Verify workstation auto-lock on front desk machines', description: 'Screens must lock after ten minutes unattended. Spot-check each terminal.', status: 'done', priority: 'medium', offsetDays: -12, locationIndex: 1, assignee: 'staff' },
  { title: 'Update notice of privacy practices posting', description: 'Waiting-room copy is on the prior version. Replace printed and portal copies.', status: 'blocked', priority: 'medium', offsetDays: -1, locationIndex: 2, assignee: 'manager' },
  { title: 'Document offsite backup restore test', description: 'Restore drill completed last month but no evidence was attached to the control.', status: 'in_progress', priority: 'high', offsetDays: 6, locationIndex: 0, assignee: 'admin' },
  { title: 'Decommission retired laptop inventory', description: 'Three laptops pulled from service need certified wipe records before disposal.', status: 'open', priority: 'medium', offsetDays: 18, locationIndex: 2, assignee: null },
  { title: 'Review third-party portal access list', description: 'Billing contractor roster changed. Remove access for anyone off the engagement.', status: 'open', priority: 'high', offsetDays: -6, locationIndex: 0, assignee: 'admin' },
  { title: 'Confirm secure disposal bins serviced', description: 'Shredding vendor missed the scheduled pickup at two sites.', status: 'done', priority: 'low', offsetDays: -20, locationIndex: 1, assignee: 'staff' },
  { title: 'Patch imaging workstation operating system', description: 'Vendor-supported update available; schedule outside clinic hours.', status: 'open', priority: 'medium', offsetDays: 9, locationIndex: 2, assignee: 'manager' },
  { title: 'Collect signed confidentiality agreements', description: 'Two contractors started without a signed agreement on file.', status: 'in_progress', priority: 'high', offsetDays: 2, locationIndex: 0, assignee: 'owner' },
  { title: 'Tabletop exercise for breach response', description: 'Run the incident-response walkthrough and capture the after-action notes.', status: 'open', priority: 'medium', offsetDays: 24, locationIndex: 0, assignee: 'admin' },
  { title: 'Audit email forwarding rules', description: 'Check for mailbox rules routing clinic mail to personal addresses.', status: 'done', priority: 'high', offsetDays: -30, locationIndex: 0, assignee: 'admin' },
  { title: 'Replace shared front-desk login', description: 'One shared account still in use at Northgate. Issue individual credentials.', status: 'blocked', priority: 'urgent', offsetDays: -8, locationIndex: 1, assignee: 'manager' },
  { title: 'Record encryption status for mobile devices', description: 'Confirm full-disk encryption on every device that touches the clinic network.', status: 'open', priority: 'medium', offsetDays: 14, locationIndex: 2, assignee: null },
  { title: 'File annual risk analysis summary', description: 'Assessment closed last cycle but the summary was never attached.', status: 'done', priority: 'medium', offsetDays: -45, locationIndex: 0, assignee: 'owner' },
  { title: 'Check visitor sign-in log retention', description: 'Logs should be retained for six years. Confirm the current archive covers that window.', status: 'open', priority: 'low', offsetDays: 30, locationIndex: 2, assignee: null },
  { title: 'Validate fax cover sheet disclaimers', description: 'Outbound cover sheets are missing the confidentiality notice at one site.', status: 'open', priority: 'low', offsetDays: 21, locationIndex: 1, assignee: 'staff' },
]

const INCIDENT_TEMPLATES: {
  title: string
  summary: string
  severity: 'low' | 'medium' | 'high' | 'critical'
  category: 'unauthorized_access' | 'lost_device' | 'phishing' | 'improper_disposal' | 'system_compromise' | 'workforce_violation' | 'other'
  discoveredDaysAgo: number
  locationIndex: number
  /** How far to walk the state machine from `reported`. */
  advanceTo: 'reported' | 'triaging' | 'contained' | 'resolved' | 'closed'
  updates: string[]
}[] = [
  {
    title: 'Phishing email reported by front desk',
    summary: 'Staff member received a credential-harvesting message impersonating the practice management vendor. Reported without clicking the link.',
    severity: 'medium', category: 'phishing', discoveredDaysAgo: 2, locationIndex: 1, advanceTo: 'triaging',
    updates: ['Message headers captured and forwarded to the mail provider for blocklisting.'],
  },
  {
    title: 'Unattended workstation left unlocked overnight',
    summary: 'Cleaning crew found a clinical workstation logged in after hours. No evidence of access by an unauthorised party.',
    severity: 'low', category: 'workforce_violation', discoveredDaysAgo: 9, locationIndex: 0, advanceTo: 'resolved',
    updates: ['Auto-lock timeout reduced to five minutes at this site.', 'Refresher reminder sent to the clinical team.'],
  },
  {
    title: 'Laptop reported missing from Northgate',
    summary: 'Encrypted laptop unaccounted for after a staff transfer. Full-disk encryption confirmed active at last check-in.',
    severity: 'high', category: 'lost_device', discoveredDaysAgo: 5, locationIndex: 1, advanceTo: 'contained',
    updates: ['Device remotely wiped and removed from the directory.', 'Encryption attestation retrieved from the management console.'],
  },
  {
    title: 'Records placed in general waste',
    summary: 'Printed schedules found in a non-secure bin. Retrieved and moved to a shredding container the same morning.',
    severity: 'medium', category: 'improper_disposal', discoveredDaysAgo: 21, locationIndex: 2, advanceTo: 'closed',
    updates: ['Secure bins added at the two print stations lacking them.', 'Disposal procedure re-briefed at the site huddle.', 'Closed after 30-day check showed no recurrence.'],
  },
  {
    title: 'Former contractor account still active',
    summary: 'Access review found an account belonging to a contractor whose engagement ended. No sign-in activity after the end date.',
    severity: 'high', category: 'unauthorized_access', discoveredDaysAgo: 1, locationIndex: 0, advanceTo: 'reported',
    updates: [],
  },
  {
    title: 'Vendor portal outage during scheduled sync',
    summary: 'Third-party portal unavailable for several hours. No data loss; queued records synced once service returned.',
    severity: 'low', category: 'other', discoveredDaysAgo: 34, locationIndex: 0, advanceTo: 'closed',
    updates: ['Vendor confirmed a regional outage on their status page.', 'Queue drained with no records dropped.'],
  },
]

const POLICY_TEMPLATES: { title: string; body: string; publish: boolean }[] = [
  { title: 'Workforce Access Control Policy', publish: true, body: '## Purpose\n\nEvery workforce member gets the minimum access needed to do their job, and no more.\n\n## Scope\n\nAll accounts across every clinic location, including contractors and temporary staff.\n\n## Requirements\n\n- Access is granted by role, not by person.\n- Every account is reviewed at least quarterly.\n- Access is removed on the last working day, not after it.\n- Shared logins are not permitted for any system that touches protected health information.' },
  { title: 'Incident Response Policy', publish: true, body: '## Purpose\n\nSet out how the practice detects, reports, and resolves a suspected privacy or security incident.\n\n## Reporting\n\nAnyone who suspects an incident reports it the same day. There is no penalty for reporting something that turns out to be nothing.\n\n## Response\n\n1. Contain the immediate risk.\n2. Record what happened and when it was found.\n3. Assess whether notification is required.\n4. Close only after the corrective action is verified.' },
  { title: 'Device and Media Handling Policy', publish: true, body: '## Purpose\n\nProtect information stored on laptops, phones, removable media, and printed material.\n\n## Requirements\n\n- Full-disk encryption on every device that stores clinic data.\n- Printed material goes into a secure disposal bin, never general waste.\n- Devices are wiped and certified before disposal or reassignment.\n- Loss or theft is reported the same day it is noticed.' },
  { title: 'Business Associate Management Policy', publish: true, body: '## Purpose\n\nEnsure every vendor that handles protected health information is under a signed agreement before access is granted.\n\n## Requirements\n\n- No production access without an executed agreement.\n- Agreements are tracked with their signature and expiry dates.\n- Renewals begin 60 days before expiry.\n- Vendor access is removed when an engagement ends.' },
  { title: 'Remote Work Policy', publish: false, body: '## Purpose\n\nDefine the conditions under which clinic work may be performed away from a practice location.\n\n## Draft note\n\nPending review by the practice administrator before publication.' },
]

const RISK_ITEMS: { category: string; description: string; likelihood: number; impact: number; mitigation: string; dueOffsetDays: number }[] = [
  { category: 'Access control', description: 'Shared front-desk account in use at one location.', likelihood: 4, impact: 4, mitigation: 'Issue individual credentials and disable the shared login.', dueOffsetDays: 14 },
  { category: 'Vendor management', description: 'Transcription vendor agreement approaching expiry.', likelihood: 3, impact: 5, mitigation: 'Start renewal 60 days ahead and track countersignature.', dueOffsetDays: 30 },
  { category: 'Device security', description: 'Encryption status unverified on several mobile devices.', likelihood: 3, impact: 4, mitigation: 'Enrol every device in management and report on encryption state.', dueOffsetDays: 21 },
  { category: 'Workforce training', description: 'New hires operating before completing annual training.', likelihood: 4, impact: 3, mitigation: 'Block system access until training is recorded complete.', dueOffsetDays: 10 },
  { category: 'Physical safeguards', description: 'Secure disposal bins missing at two print stations.', likelihood: 2, impact: 3, mitigation: 'Install bins and add them to the site opening checklist.', dueOffsetDays: 7 },
  { category: 'Contingency planning', description: 'Backup restore tested but not evidenced.', likelihood: 2, impact: 5, mitigation: 'Attach restore output to the contingency control each quarter.', dueOffsetDays: 45 },
  { category: 'Audit controls', description: 'Audit log export not reviewed on a set cadence.', likelihood: 3, impact: 2, mitigation: 'Assign a monthly reviewer and record the review.', dueOffsetDays: 60 },
  { category: 'Transmission security', description: 'Fax cover sheets missing confidentiality notice at one site.', likelihood: 2, impact: 2, mitigation: 'Replace the template and remove old stock.', dueOffsetDays: 12 },
]

const TRAINING_COURSES: { title: string; description: string; frequencyDays: number }[] = [
  { title: 'Annual HIPAA Privacy and Security Awareness', description: 'Core annual training covering the Privacy Rule, the Security Rule, and how to report a suspected incident.', frequencyDays: 365 },
  { title: 'Phishing and Social Engineering Refresher', description: 'How to recognise credential-harvesting attempts and what to do when one arrives.', frequencyDays: 180 },
  { title: 'Secure Handling of Printed Material', description: 'Printing, transporting, storing, and disposing of physical records.', frequencyDays: 365 },
]

const VENDOR_TEMPLATES: {
  name: string
  website: string
  dataCategories: string[]
  /** null = no agreement on file yet; the register shows this as missing. */
  baa: { signedDaysAgo: number; expiresInDays: number | null } | null
}[] = [
  { name: 'Cascade Transcription Services', website: 'https://example.com/cascade', dataCategories: ['Clinical notes'], baa: { signedDaysAgo: 305, expiresInDays: 32 } },
  { name: 'Meridian Billing Partners', website: 'https://example.com/meridian', dataCategories: ['Claims', 'Demographics'], baa: { signedDaysAgo: 120, expiresInDays: 245 } },
  { name: 'Northstar Secure Shredding', website: 'https://example.com/northstar', dataCategories: ['Printed records'], baa: { signedDaysAgo: 200, expiresInDays: 165 } },
  { name: 'Harbor Cloud Backup', website: 'https://example.com/harbor', dataCategories: ['Backups'], baa: { signedDaysAgo: 60, expiresInDays: 305 } },
  { name: 'Trailhead IT Support', website: 'https://example.com/trailhead', dataCategories: ['Remote support'], baa: { signedDaysAgo: 430, expiresInDays: -65 } },
  { name: 'Junction Appointment Reminders', website: 'https://example.com/junction', dataCategories: ['Demographics'], baa: null },
]

/** Controls that get evidence attached. The remaining three stay uncovered so the coverage tile is not a flat 100%. */
const EVIDENCED_CONTROLS = ['CC1.1', 'CC2.1', 'CC5.1', 'CC6.1', 'CC6.2', 'CC7.2', 'CC9.1'] as const

// ── teardown ────────────────────────────────────────────────────────────────

/**
 * The seed builds from clean rather than upserting, so a previous run has to go
 * first. That is only possible while the tenant has no audit history:
 * `audit_events.tenant_id` carries a foreign key to `organizations`, and the
 * table is append-only behind a Postgres trigger, so once the demo org has
 * written a single audit event it can no longer be deleted.
 *
 * That is the audit-immutability guarantee doing its job, not a bug. Re-seeding
 * therefore needs a fresh database:
 *
 *   node scripts/reset-local-db.mjs phiguard_demo
 */
async function resetDemoWorkspace(db: DB) {
  const [existing] = await db
    .select({ id: organizations.id })
    .from(organizations)
    .where(eq(organizations.slug, DEMO_ORG_SLUG))
    .limit(1)

  if (existing) {
    const [{ count: auditCount }] = await db
      .select({ count: count() })
      .from(auditEvents)
      .where(eq(auditEvents.tenantId, existing.id))

    if (auditCount > 0) {
      throw new Error(
        `The demo organization already exists and has ${auditCount} audit events, which are `
        + 'append-only and pin the tenant row in place. Recreate the database first:\n\n'
        + '  node scripts/reset-local-db.mjs phiguard_demo\n',
      )
    }

    // soc2_evidence.tenant_id has no foreign key, so it will not cascade.
    await db.delete(soc2Evidence).where(eq(soc2Evidence.tenantId, existing.id))
    await db.delete(organizations).where(eq(organizations.id, existing.id))
  }

  const emails = PEOPLE.map((person) => person.email)
  await db.delete(users).where(inArray(users.email, emails))
}

// ── build ───────────────────────────────────────────────────────────────────

async function createPeople(db: DB) {
  const people: (DemoPerson & { id: string })[] = []

  for (const definition of PEOPLE) {
    const name = `${faker.person.firstName()} ${faker.person.lastName()}`

    const [user] = await db
      .insert(users)
      .values({ email: definition.email, name, emailVerified: true, emailVerifiedAt: new Date() })
      .returning()

    await db.insert(accounts).values({
      userId: user.id,
      accountId: definition.email,
      providerId: 'credential',
      password: await hashPassword(DEMO_PASSWORD),
    })

    people.push({ ...definition, name, id: user.id })
  }

  return people
}

async function createOrganization(db: DB, ownerId: string) {
  const [organization] = await db
    .insert(organizations)
    .values({
      name: DEMO_ORG_NAME,
      slug: DEMO_ORG_SLUG,
      // Group unlocks the compliance program and SOC 2 surfaces, which is what
      // makes the demo worth screenshotting.
      plan: 'group',
      planStatus: 'active',
      maxMembers: 25,
      planSelectedAt: daysAgo(210),
      termsAcceptedAt: daysAgo(210),
      termsAcceptedByUserId: ownerId,
      baaSignedAt: daysAgo(210),
      baaSignedByUserId: ownerId,
    })
    .returning()

  return organization
}

async function acceptLegalDocuments(db: DB, tenantId: string, owner: DemoPerson & { id: string }) {
  await db.insert(legalAcceptances).values(
    getStandardLegalDocuments().map((document) => ({
      tenantId,
      documentType: document.type,
      documentVersion: document.version,
      documentTitle: document.title,
      contentHash: hashDocument(document),
      customerEntityName: DEMO_ORG_NAME,
      signerName: owner.name,
      signerTitle: owner.title,
      signerEmail: owner.email,
      acceptedByUserId: owner.id,
      acceptedAt: daysAgo(210),
      snapshot: document,
    })),
  )
}

async function createLocationsAndMemberships(
  db: DB,
  tenantId: string,
  people: (DemoPerson & { id: string })[],
) {
  const createdLocations = await db
    .insert(locations)
    .values(LOCATION_DEFINITIONS.map((location) => ({ ...location, organizationId: tenantId })))
    .returning()

  for (const person of people) {
    const [membership] = await db
      .insert(memberships)
      .values({ userId: person.id, tenantId, role: person.role, acceptedAt: daysAgo(180) })
      .returning()

    // Only location-scoped roles need grants; org-wide roles resolve every
    // active location without them.
    const needsGrants = person.role === 'location_manager' || person.role === 'location_staff'
    if (!needsGrants) continue

    await db.insert(locationGrants).values(
      person.locationIndexes.map((index) => ({
        tenantId,
        membershipId: membership.id,
        locationId: createdLocations[index].id,
      })),
    )
  }

  return createdLocations
}

async function seedTasks(
  db: DB,
  tenantId: string,
  locationIds: string[],
  byKey: Map<string, DemoPerson & { id: string }>,
) {
  const owner = byKey.get('owner')!
  let commentsAdded = 0

  for (const template of TASK_TEMPLATES) {
    const creator = byKey.get(template.assignee ?? 'owner') ?? owner

    const task = await createTask(db, {
      tenantId,
      locationId: locationIds[template.locationIndex],
      title: template.title,
      description: template.description,
      priority: template.priority,
      dueAt: daysFromNow(template.offsetDays),
      createdBy: creator.id,
    })

    if (template.assignee) {
      const assignee = byKey.get(template.assignee)!
      await assignTask(db, { taskId: task.id, tenantId, userId: assignee.id, assignedBy: owner.id })
    }

    // createTask always starts a task at 'open'; move it through the real
    // status mutation so the change lands in the audit log.
    if (template.status !== 'open') {
      await updateTaskStatus(db, { taskId: task.id, tenantId, actorId: creator.id, status: template.status })
    }

    if (template.status === 'blocked') {
      await addComment(db, {
        taskId: task.id,
        tenantId,
        authorId: creator.id,
        body: 'Blocked pending the vendor response. Will revisit once we have a date.',
      })
      commentsAdded += 1
    }
  }

  return { tasks: TASK_TEMPLATES.length, comments: commentsAdded }
}

async function seedChecklists(
  db: DB,
  tenantId: string,
  locationIds: string[],
  actorId: string,
) {
  await runSeed(db)

  await assignChecklistTemplateToLocations(db, {
    tenantId,
    templateId: STARTER_TEMPLATES.accessReview,
    locationIds,
    actorId,
    dueAt: daysFromNow(12),
  })
  await assignChecklistTemplateToLocations(db, {
    tenantId,
    templateId: STARTER_TEMPLATES.baaInventory,
    locationIds: [locationIds[0]],
    actorId,
    dueAt: daysFromNow(25),
  })
  await assignChecklistTemplateToLocations(db, {
    tenantId,
    templateId: STARTER_TEMPLATES.trainingLog,
    locationIds: [locationIds[0], locationIds[1]],
    actorId,
    dueAt: daysAgo(2),
  })

  // Partially complete the work so progress bars show real intermediate state
  // rather than 0% or 100% everywhere.
  const allChecklists = await db
    .select({ id: checklists.id })
    .from(checklists)
    .where(eq(checklists.tenantId, tenantId))

  let completed = 0
  for (const [index, checklist] of allChecklists.entries()) {
    const items = await db
      .select({ id: checklistItems.id })
      .from(checklistItems)
      .where(and(eq(checklistItems.checklistId, checklist.id), eq(checklistItems.tenantId, tenantId)))

    // Vary completion per checklist: none, some, or all.
    const target = [0, 1, 2, 3][index % 4]
    for (const item of items.slice(0, Math.min(target, items.length))) {
      await completeItem(db, { itemId: item.id, tenantId, actorId })
      completed += 1
    }
  }

  return { checklists: allChecklists.length, itemsCompleted: completed }
}

async function seedIncidents(
  db: DB,
  tenantId: string,
  locationIds: string[],
  byKey: Map<string, DemoPerson & { id: string }>,
) {
  const admin = byKey.get('admin')!
  const order: Array<'triaging' | 'contained' | 'resolved' | 'closed'> = [
    'triaging',
    'contained',
    'resolved',
    'closed',
  ]

  for (const template of INCIDENT_TEMPLATES) {
    const incident = await createIncident(db, {
      tenantId,
      locationId: locationIds[template.locationIndex],
      title: template.title,
      summary: template.summary,
      severity: template.severity,
      category: template.category,
      discoveredAt: daysAgo(template.discoveredDaysAgo),
      discoveredBy: admin.id,
      actorId: admin.id,
    })

    // The state machine only allows one step at a time, so walk it. Each step
    // writes its own audit event, which is the point.
    const stopAt = order.indexOf(template.advanceTo as (typeof order)[number])
    for (let step = 0; step <= stopAt; step += 1) {
      await transitionIncident(db, {
        incidentId: incident.id,
        tenantId,
        actorId: admin.id,
        toStatus: order[step],
      })
    }
  }

  return { incidents: INCIDENT_TEMPLATES.length }
}

async function seedProgram(
  db: DB,
  tenantId: string,
  byKey: Map<string, DemoPerson & { id: string }>,
  people: (DemoPerson & { id: string })[],
) {
  const owner = byKey.get('owner')!
  const admin = byKey.get('admin')!

  // ── policies ──
  let published = 0
  for (const template of POLICY_TEMPLATES) {
    const policy = await createPolicy(db, {
      tenantId,
      actorId: admin.id,
      title: template.title,
      bodyMarkdown: template.body,
      version: '1.0',
      effectiveDate: daysAgo(150),
      requiresAcknowledgement: true,
    })

    if (!template.publish) continue

    await publishPolicy(db, { policyId: policy.id, tenantId, actorId: admin.id })
    published += 1

    // Most but not all staff have acknowledged, so the pending count is non-zero.
    // Routed through acknowledgePolicy rather than inserted directly, so each
    // acknowledgement writes its policy.acknowledged audit event like a real
    // one. That costs the backdated acknowledgedAt the domain function does not
    // accept, which is the right trade: the audit trail these screenshots show
    // has to be genuine.
    for (const person of people.slice(0, 3)) {
      await acknowledgePolicy(db, { policyId: policy.id, userId: person.id, tenantId })
    }
  }

  // ── risk register ──
  const assessment = await createRiskAssessment(db, {
    tenantId,
    actorId: admin.id,
    title: `Annual Security Risk Analysis ${now.getFullYear()}`,
  })

  for (const item of RISK_ITEMS) {
    await createRiskItem(db, {
      tenantId,
      actorId: admin.id,
      assessmentId: assessment.id,
      category: item.category,
      description: item.description,
      likelihood: item.likelihood,
      impact: item.impact,
      mitigation: item.mitigation,
      ownerId: admin.id,
      dueAt: daysFromNow(item.dueOffsetDays),
    })
  }

  // ── training ──
  let recordsCompleted = 0
  for (const [courseIndex, courseTemplate] of TRAINING_COURSES.entries()) {
    const course = await createTrainingCourse(db, {
      tenantId,
      actorId: admin.id,
      title: courseTemplate.title,
      description: courseTemplate.description,
      frequencyDays: courseTemplate.frequencyDays,
    })

    for (const [personIndex, person] of people.entries()) {
      // Stagger due dates so the register shows overdue, due-soon, and ok rows.
      const dueOffset = [-9, 6, 40, 120, 200][(personIndex + courseIndex) % 5]

      const record = await assignCourse(db, {
        tenantId,
        actorId: admin.id,
        userId: person.id,
        courseId: course.id,
        dueAt: daysFromNow(dueOffset),
      })

      // Complete roughly half, leaving the rest not-started or overdue.
      if ((personIndex + courseIndex) % 2 !== 0) continue

      await markCompleted(db, {
        recordId: record.id,
        actorId: admin.id,
        actorUserId: admin.id,
        actorCanManageAllUsers: true,
        tenantId,
      })
      recordsCompleted += 1
    }
  }

  // ── vendors ──
  for (const template of VENDOR_TEMPLATES) {
    const vendor = await createVendor(db, {
      tenantId,
      actorId: owner.id,
      name: template.name,
      website: template.website,
      contactEmail: `contracts@${new URL(template.website).hostname}`,
      dataCategories: template.dataCategories,
    })

    if (!template.baa) continue

    await recordBaa(db, {
      vendorId: vendor.id,
      tenantId,
      actorId: owner.id,
      signedAt: daysAgo(template.baa.signedDaysAgo),
      signerName: owner.name,
      signerEmail: owner.email,
      expiresAt: template.baa.expiresInDays === null ? undefined : daysFromNow(template.baa.expiresInDays),
    })
  }

  return { policiesPublished: published, riskItems: RISK_ITEMS.length, trainingCompleted: recordsCompleted }
}

async function seedSoc2(
  db: DB,
  tenantId: string,
  byKey: Map<string, DemoPerson & { id: string }>,
) {
  const admin = byKey.get('admin')!

  await seedSoc2Controls(db)

  for (const controlId of EVIDENCED_CONTROLS) {
    // fileKey must sit under the tenant's evidence prefix or the UI renders it
    // as an invalid artifact.
    const fileKey = `evidence/${tenantId}/soc2/${controlId.toLowerCase().replace('.', '-')}-attestation.pdf`

    await recordManualEvidence(db, {
      tenantId,
      actorId: admin.id,
      controlId,
      fileKey,
      summary: `Signed attestation and supporting export for ${controlId}.`,
    })
  }

  const review = await openAccessReview(db, {
    tenantId,
    actorId: admin.id,
    periodStart: daysAgo(90),
    periodEnd: now,
  })

  return { controlsEvidenced: EVIDENCED_CONTROLS.length, accessReviewId: review.reviewId }
}

// ── entrypoint ──────────────────────────────────────────────────────────────

export type DemoSeedResult = {
  organizationId: string
  organizationName: string
  locationIds: string[]
  people: { key: string; id: string; email: string; name: string; role: DemoRole }[]
  password: string
  counts: Record<string, number>
}

export async function seedDemoWorkspace(db: DB): Promise<DemoSeedResult> {
  faker.seed(FAKER_SEED)

  await resetDemoWorkspace(db)

  const people = await createPeople(db)
  const byKey = new Map(people.map((person) => [person.key, person]))
  const owner = byKey.get('owner')!

  const organization = await createOrganization(db, owner.id)
  await acceptLegalDocuments(db, organization.id, owner)

  const createdLocations = await createLocationsAndMemberships(db, organization.id, people)
  const locationIds = createdLocations.map((location) => location.id)

  // Everything below writes audit events. Running inside an audit context means
  // they carry a real actor rather than an anonymous one.
  const counts = await withAuditContext({ actorId: owner.id }, async () => {
    const taskCounts = await seedTasks(db, organization.id, locationIds, byKey)
    const checklistCounts = await seedChecklists(db, organization.id, locationIds, owner.id)
    const incidentCounts = await seedIncidents(db, organization.id, locationIds, byKey)
    const programCounts = await seedProgram(db, organization.id, byKey, people)
    const soc2Counts = await seedSoc2(db, organization.id, byKey)

    return {
      locations: createdLocations.length,
      members: people.length,
      ...taskCounts,
      ...checklistCounts,
      ...incidentCounts,
      ...programCounts,
      controlsEvidenced: soc2Counts.controlsEvidenced,
    }
  })

  return {
    organizationId: organization.id,
    organizationName: organization.name,
    locationIds,
    people: people.map(({ key, id, email, name, role }) => ({ key, id, email, name, role })),
    password: DEMO_PASSWORD,
    counts,
  }
}

/**
 * `getDb()` returns a lazily-created singleton whose postgres.js pool keeps the
 * event loop alive, so a CLI run has to close it explicitly or the process
 * hangs after the work is done.
 */
async function closeDb(db: DB) {
  const client = (db as unknown as { $client?: { end?: () => Promise<void> } }).$client
  await client?.end?.()
}

async function main() {
  const db = getDb()
  const result = await seedDemoWorkspace(db)

  console.log('')
  console.log(`✓ Demo workspace seeded: ${result.organizationName}`)
  console.log('')
  console.log('  Sign in with any of these (same password):')
  for (const person of result.people) {
    console.log(`    ${person.role.padEnd(17)} ${person.email.padEnd(30)} ${person.name}`)
  }
  console.log(`    password          ${result.password}`)
  console.log('')
  console.log('  Seeded:')
  for (const [key, value] of Object.entries(result.counts)) {
    console.log(`    ${key.padEnd(20)} ${value}`)
  }
  console.log('')

  await closeDb(db)
}

// Only run as a CLI when invoked directly; the screenshot spec imports
// seedDemoWorkspace instead.
const invokedDirectly = process.argv[1]?.replace(/\\/g, '/').endsWith('scripts/demo-seed.ts')
if (invokedDirectly) {
  main().catch((error) => {
    console.error('Demo seed failed:', error)
    process.exit(1)
  })
}
