/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AcceptInviteInvitationIdRouteImport } from './routes/accept-invite.$invitationId'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppHelpRouteImport } from './routes/app/help'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppTasksRouteImport } from './routes/app/tasks'
import { Route as PartnerCodeRouteImport } from './routes/partner.$code'
import { Route as PartnerDashboardRouteImport } from './routes/partner.dashboard'
import { Route as PartnerLoginRouteImport } from './routes/partner.login'
import { Route as PartnerVerifyRouteImport } from './routes/partner.verify'
import { Route as SignupCheckEmailRouteImport } from './routes/signup.check-email'
import { Route as ApiAiCsContextRouteImport } from './routes/api/ai-cs/context'
import { Route as ApiAnalyticsProductRouteImport } from './routes/api/analytics/product'
import { Route as ApiAuditExportRouteImport } from './routes/api/audit.export'
import { Route as ApiMarketingLeadsRouteImport } from './routes/api/marketing/leads'
import { Route as ApiMarketingPromotionRouteImport } from './routes/api/marketing/promotion'
import { Route as ApiMarketingResendWebhookRouteImport } from './routes/api/marketing/resend-webhook'
import { Route as ApiMarketingUnsubscribeRouteImport } from './routes/api/marketing/unsubscribe'
import { Route as ApiPartnersApplyRouteImport } from './routes/api/partners.apply'
import { Route as ApiSoc2BundlesRouteImport } from './routes/api/soc2/bundles'
import { Route as ApiUploadsDirectRouteImport } from './routes/api/uploads.direct'
import { Route as ApiUploadsMockRouteImport } from './routes/api/uploads.mock'
import { Route as ApiUploadsScanResultRouteImport } from './routes/api/uploads.scan-result'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as AppAdminPartnersRouteImport } from './routes/app/admin.partners'
import { Route as AppAuditIndexRouteImport } from './routes/app/audit/index'
import { Route as AppAuditExportRouteImport } from './routes/app/audit/export'
import { Route as AppComplianceIndexRouteImport } from './routes/app/compliance/index'
import { Route as AppReportsIndexRouteImport } from './routes/app/reports.index'
import { Route as AppReportsComplianceRouteImport } from './routes/app/reports.compliance'
import { Route as AppReportsTasksRouteImport } from './routes/app/reports.tasks'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings.index'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/app/settings.integrations'
import { Route as AppSettingsLocationsRouteImport } from './routes/app/settings.locations'
import { Route as AppSettingsMembersRouteImport } from './routes/app/settings.members'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings.profile'
import { Route as AppSettingsSecurityKeysRouteImport } from './routes/app/settings.security-keys'
import { Route as AppSoc2IndexRouteImport } from './routes/app/soc2.index'
import { Route as AppSoc2AccessReviewsRouteImport } from './routes/app/soc2.access-reviews'
import { Route as AppSoc2AuditorRouteImport } from './routes/app/soc2.auditor'
import { Route as AppSoc2ControlsRouteImport } from './routes/app/soc2.controls'
import { Route as AppSoc2EvidenceRouteImport } from './routes/app/soc2.evidence'
import { Route as AppTasksTaskIdRouteImport } from './routes/app/tasks.$taskId'
import { Route as AppTasksNewRouteImport } from './routes/app/tasks.new'
import { Route as ApiAiCsV1ChatRouteImport } from './routes/api/ai-cs/v1/chat'
import { Route as ApiAiCsV1EscalationsRouteImport } from './routes/api/ai-cs/v1/escalations'
import { Route as ApiAiCsV1SessionsRouteImport } from './routes/api/ai-cs/v1/sessions'
import { Route as ApiIntegrationsProviderCallbackRouteImport } from './routes/api/integrations/$provider.callback'
import { Route as ApiMarketingLeadMagnetsSlugRouteImport } from './routes/api/marketing/lead-magnets.$slug'
import { Route as AppComplianceChecklistsIndexRouteImport } from './routes/app/compliance/checklists.index'
import { Route as AppComplianceChecklistsChecklistIdRouteImport } from './routes/app/compliance/checklists.$checklistId'
import { Route as AppComplianceIncidentsIndexRouteImport } from './routes/app/compliance/incidents/index'
import { Route as AppComplianceIncidentsIncidentIdRouteImport } from './routes/app/compliance/incidents/$incidentId'
import { Route as AppComplianceIncidentsNewRouteImport } from './routes/app/compliance/incidents/new'
import { Route as AppCompliancePoliciesIndexRouteImport } from './routes/app/compliance/policies/index'
import { Route as AppComplianceProgramIndexRouteImport } from './routes/app/compliance/program.index'
import { Route as AppComplianceProgramPoliciesRouteImport } from './routes/app/compliance/program.policies'
import { Route as AppComplianceProgramRiskRouteImport } from './routes/app/compliance/program.risk'
import { Route as AppComplianceProgramTrainingRouteImport } from './routes/app/compliance/program.training'
import { Route as AppComplianceProgramVendorsRouteImport } from './routes/app/compliance/program.vendors'
import { Route as AppSoc2AccessReviewsIndexRouteImport } from './routes/app/soc2.access-reviews.index'
import { Route as AppSoc2AccessReviewsReviewIdRouteImport } from './routes/app/soc2.access-reviews.$reviewId'
import { Route as AppComplianceProgramPoliciesIndexRouteImport } from './routes/app/compliance/program.policies.index'
import { Route as AppComplianceProgramPoliciesPolicyIdRouteImport } from './routes/app/compliance/program.policies.$policyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteInvitationIdRoute =
  AcceptInviteInvitationIdRouteImport.update({
    id: '/accept-invite/$invitationId',
    path: '/accept-invite/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const PartnerCodeRoute = PartnerCodeRouteImport.update({
  id: '/partner/$code',
  path: '/partner/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner/dashboard',
  path: '/partner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/partner/login',
  path: '/partner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerVerifyRoute = PartnerVerifyRouteImport.update({
  id: '/partner/verify',
  path: '/partner/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupCheckEmailRoute = SignupCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => SignupRoute,
} as any)
const ApiAiCsContextRoute = ApiAiCsContextRouteImport.update({
  id: '/api/ai-cs/context',
  path: '/api/ai-cs/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsProductRoute = ApiAnalyticsProductRouteImport.update({
  id: '/api/analytics/product',
  path: '/api/analytics/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditExportRoute = ApiAuditExportRouteImport.update({
  id: '/api/audit/export',
  path: '/api/audit/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingLeadsRoute = ApiMarketingLeadsRouteImport.update({
  id: '/api/marketing/leads',
  path: '/api/marketing/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingPromotionRoute = ApiMarketingPromotionRouteImport.update({
  id: '/api/marketing/promotion',
  path: '/api/marketing/promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingResendWebhookRoute =
  ApiMarketingResendWebhookRouteImport.update({
    id: '/api/marketing/resend-webhook',
    path: '/api/marketing/resend-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketingUnsubscribeRoute = ApiMarketingUnsubscribeRouteImport.update({
  id: '/api/marketing/unsubscribe',
  path: '/api/marketing/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPartnersApplyRoute = ApiPartnersApplyRouteImport.update({
  id: '/api/partners/apply',
  path: '/api/partners/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoc2BundlesRoute = ApiSoc2BundlesRouteImport.update({
  id: '/api/soc2/bundles',
  path: '/api/soc2/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsDirectRoute = ApiUploadsDirectRouteImport.update({
  id: '/api/uploads/direct',
  path: '/api/uploads/direct',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsMockRoute = ApiUploadsMockRouteImport.update({
  id: '/api/uploads/mock',
  path: '/api/uploads/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsScanResultRoute = ApiUploadsScanResultRouteImport.update({
  id: '/api/uploads/scan-result',
  path: '/api/uploads/scan-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminPartnersRoute = AppAdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditExportRoute = AppAuditExportRouteImport.update({
  id: '/audit/export',
  path: '/audit/export',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceIndexRoute = AppComplianceIndexRouteImport.update({
  id: '/compliance/',
  path: '/compliance/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsComplianceRoute = AppReportsComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsTasksRoute = AppReportsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLocationsRoute = AppSettingsLocationsRouteImport.update({
  id: '/settings/locations',
  path: '/settings/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityKeysRoute = AppSettingsSecurityKeysRouteImport.update({
  id: '/settings/security-keys',
  path: '/settings/security-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppSoc2IndexRoute = AppSoc2IndexRouteImport.update({
  id: '/soc2/',
  path: '/soc2/',
  getParentRoute: () => AppRoute,
} as any)
const AppSoc2AccessReviewsRoute = AppSoc2AccessReviewsRouteImport.update({
  id: '/soc2/access-reviews',
  path: '/soc2/access-reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppSoc2AuditorRoute = AppSoc2AuditorRouteImport.update({
  id: '/soc2/auditor',
  path: '/soc2/auditor',
  getParentRoute: () => AppRoute,
} as any)
const AppSoc2ControlsRoute = AppSoc2ControlsRouteImport.update({
  id: '/soc2/controls',
  path: '/soc2/controls',
  getParentRoute: () => AppRoute,
} as any)
const AppSoc2EvidenceRoute = AppSoc2EvidenceRouteImport.update({
  id: '/soc2/evidence',
  path: '/soc2/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksNewRoute = AppTasksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTasksRoute,
} as any)
const ApiAiCsV1ChatRoute = ApiAiCsV1ChatRouteImport.update({
  id: '/api/ai-cs/v1/chat',
  path: '/api/ai-cs/v1/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCsV1EscalationsRoute = ApiAiCsV1EscalationsRouteImport.update({
  id: '/api/ai-cs/v1/escalations',
  path: '/api/ai-cs/v1/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCsV1SessionsRoute = ApiAiCsV1SessionsRouteImport.update({
  id: '/api/ai-cs/v1/sessions',
  path: '/api/ai-cs/v1/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsProviderCallbackRoute =
  ApiIntegrationsProviderCallbackRouteImport.update({
    id: '/api/integrations/$provider/callback',
    path: '/api/integrations/$provider/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketingLeadMagnetsSlugRoute =
  ApiMarketingLeadMagnetsSlugRouteImport.update({
    id: '/api/marketing/lead-magnets/$slug',
    path: '/api/marketing/lead-magnets/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppComplianceChecklistsIndexRoute =
  AppComplianceChecklistsIndexRouteImport.update({
    id: '/compliance/checklists/',
    path: '/compliance/checklists/',
    getParentRoute: () => AppRoute,
  } as any)
const AppComplianceChecklistsChecklistIdRoute =
  AppComplianceChecklistsChecklistIdRouteImport.update({
    id: '/compliance/checklists/$checklistId',
    path: '/compliance/checklists/$checklistId',
    getParentRoute: () => AppRoute,
  } as any)
const AppComplianceIncidentsIndexRoute =
  AppComplianceIncidentsIndexRouteImport.update({
    id: '/compliance/incidents/',
    path: '/compliance/incidents/',
    getParentRoute: () => AppRoute,
  } as any)
const AppComplianceIncidentsIncidentIdRoute =
  AppComplianceIncidentsIncidentIdRouteImport.update({
    id: '/compliance/incidents/$incidentId',
    path: '/compliance/incidents/$incidentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppComplianceIncidentsNewRoute =
  AppComplianceIncidentsNewRouteImport.update({
    id: '/compliance/incidents/new',
    path: '/compliance/incidents/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppCompliancePoliciesIndexRoute =
  AppCompliancePoliciesIndexRouteImport.update({
    id: '/compliance/policies/',
    path: '/compliance/policies/',
    getParentRoute: () => AppRoute,
  } as any)
const AppComplianceProgramIndexRoute =
  AppComplianceProgramIndexRouteImport.update({
    id: '/compliance/program/',
    path: '/compliance/program/',
    getParentRoute: () => AppRoute,
  } as any)
const AppComplianceProgramPoliciesRoute =
  AppComplianceProgramPoliciesRouteImport.update({
    id: '/compliance/program/policies',
    path: '/compliance/program/policies',
    getParentRoute: () => AppRoute,
  } as any)
const AppComplianceProgramRiskRoute =
  AppComplianceProgramRiskRouteImport.update({
    id: '/compliance/program/risk',
    path: '/compliance/program/risk',
    getParentRoute: () => AppRoute,
  } as any)
const AppComplianceProgramTrainingRoute =
  AppComplianceProgramTrainingRouteImport.update({
    id: '/compliance/program/training',
    path: '/compliance/program/training',
    getParentRoute: () => AppRoute,
  } as any)
const AppComplianceProgramVendorsRoute =
  AppComplianceProgramVendorsRouteImport.update({
    id: '/compliance/program/vendors',
    path: '/compliance/program/vendors',
    getParentRoute: () => AppRoute,
  } as any)
const AppSoc2AccessReviewsIndexRoute =
  AppSoc2AccessReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSoc2AccessReviewsRoute,
  } as any)
const AppSoc2AccessReviewsReviewIdRoute =
  AppSoc2AccessReviewsReviewIdRouteImport.update({
    id: '/$reviewId',
    path: '/$reviewId',
    getParentRoute: () => AppSoc2AccessReviewsRoute,
  } as any)
const AppComplianceProgramPoliciesIndexRoute =
  AppComplianceProgramPoliciesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppComplianceProgramPoliciesRoute,
  } as any)
const AppComplianceProgramPoliciesPolicyIdRoute =
  AppComplianceProgramPoliciesPolicyIdRouteImport.update({
    id: '/$policyId',
    path: '/$policyId',
    getParentRoute: () => AppComplianceProgramPoliciesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/readyz': typeof ReadyzRoute
  '/signup': typeof SignupRouteWithChildren
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/help': typeof AppHelpRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/tasks': typeof AppTasksRouteWithChildren
  '/partner/$code': typeof PartnerCodeRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/verify': typeof PartnerVerifyRoute
  '/signup/check-email': typeof SignupCheckEmailRoute
  '/api/ai-cs/context': typeof ApiAiCsContextRoute
  '/api/analytics/product': typeof ApiAnalyticsProductRoute
  '/api/audit/export': typeof ApiAuditExportRoute
  '/api/marketing/leads': typeof ApiMarketingLeadsRoute
  '/api/marketing/promotion': typeof ApiMarketingPromotionRoute
  '/api/marketing/resend-webhook': typeof ApiMarketingResendWebhookRoute
  '/api/marketing/unsubscribe': typeof ApiMarketingUnsubscribeRoute
  '/api/partners/apply': typeof ApiPartnersApplyRoute
  '/api/soc2/bundles': typeof ApiSoc2BundlesRoute
  '/api/uploads/direct': typeof ApiUploadsDirectRoute
  '/api/uploads/mock': typeof ApiUploadsMockRoute
  '/api/uploads/scan-result': typeof ApiUploadsScanResultRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/app/admin/partners': typeof AppAdminPartnersRoute
  '/app/audit/export': typeof AppAuditExportRoute
  '/app/reports/compliance': typeof AppReportsComplianceRoute
  '/app/reports/tasks': typeof AppReportsTasksRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/locations': typeof AppSettingsLocationsRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security-keys': typeof AppSettingsSecurityKeysRoute
  '/app/soc2/access-reviews': typeof AppSoc2AccessReviewsRouteWithChildren
  '/app/soc2/auditor': typeof AppSoc2AuditorRoute
  '/app/soc2/controls': typeof AppSoc2ControlsRoute
  '/app/soc2/evidence': typeof AppSoc2EvidenceRoute
  '/app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/app/tasks/new': typeof AppTasksNewRoute
  '/app/audit/': typeof AppAuditIndexRoute
  '/app/compliance/': typeof AppComplianceIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/soc2/': typeof AppSoc2IndexRoute
  '/api/ai-cs/v1/chat': typeof ApiAiCsV1ChatRoute
  '/api/ai-cs/v1/escalations': typeof ApiAiCsV1EscalationsRoute
  '/api/ai-cs/v1/sessions': typeof ApiAiCsV1SessionsRoute
  '/api/integrations/$provider/callback': typeof ApiIntegrationsProviderCallbackRoute
  '/api/marketing/lead-magnets/$slug': typeof ApiMarketingLeadMagnetsSlugRoute
  '/app/compliance/checklists/$checklistId': typeof AppComplianceChecklistsChecklistIdRoute
  '/app/compliance/incidents/$incidentId': typeof AppComplianceIncidentsIncidentIdRoute
  '/app/compliance/incidents/new': typeof AppComplianceIncidentsNewRoute
  '/app/compliance/program/policies': typeof AppComplianceProgramPoliciesRouteWithChildren
  '/app/compliance/program/risk': typeof AppComplianceProgramRiskRoute
  '/app/compliance/program/training': typeof AppComplianceProgramTrainingRoute
  '/app/compliance/program/vendors': typeof AppComplianceProgramVendorsRoute
  '/app/soc2/access-reviews/$reviewId': typeof AppSoc2AccessReviewsReviewIdRoute
  '/app/compliance/checklists/': typeof AppComplianceChecklistsIndexRoute
  '/app/compliance/incidents/': typeof AppComplianceIncidentsIndexRoute
  '/app/compliance/policies/': typeof AppCompliancePoliciesIndexRoute
  '/app/compliance/program/': typeof AppComplianceProgramIndexRoute
  '/app/soc2/access-reviews/': typeof AppSoc2AccessReviewsIndexRoute
  '/app/compliance/program/policies/$policyId': typeof AppComplianceProgramPoliciesPolicyIdRoute
  '/app/compliance/program/policies/': typeof AppComplianceProgramPoliciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/readyz': typeof ReadyzRoute
  '/signup': typeof SignupRouteWithChildren
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/help': typeof AppHelpRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/tasks': typeof AppTasksRouteWithChildren
  '/partner/$code': typeof PartnerCodeRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/verify': typeof PartnerVerifyRoute
  '/signup/check-email': typeof SignupCheckEmailRoute
  '/api/ai-cs/context': typeof ApiAiCsContextRoute
  '/api/analytics/product': typeof ApiAnalyticsProductRoute
  '/api/audit/export': typeof ApiAuditExportRoute
  '/api/marketing/leads': typeof ApiMarketingLeadsRoute
  '/api/marketing/promotion': typeof ApiMarketingPromotionRoute
  '/api/marketing/resend-webhook': typeof ApiMarketingResendWebhookRoute
  '/api/marketing/unsubscribe': typeof ApiMarketingUnsubscribeRoute
  '/api/partners/apply': typeof ApiPartnersApplyRoute
  '/api/soc2/bundles': typeof ApiSoc2BundlesRoute
  '/api/uploads/direct': typeof ApiUploadsDirectRoute
  '/api/uploads/mock': typeof ApiUploadsMockRoute
  '/api/uploads/scan-result': typeof ApiUploadsScanResultRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/app/admin/partners': typeof AppAdminPartnersRoute
  '/app/audit/export': typeof AppAuditExportRoute
  '/app/reports/compliance': typeof AppReportsComplianceRoute
  '/app/reports/tasks': typeof AppReportsTasksRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/locations': typeof AppSettingsLocationsRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security-keys': typeof AppSettingsSecurityKeysRoute
  '/app/soc2/auditor': typeof AppSoc2AuditorRoute
  '/app/soc2/controls': typeof AppSoc2ControlsRoute
  '/app/soc2/evidence': typeof AppSoc2EvidenceRoute
  '/app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/app/tasks/new': typeof AppTasksNewRoute
  '/app/audit': typeof AppAuditIndexRoute
  '/app/compliance': typeof AppComplianceIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/soc2': typeof AppSoc2IndexRoute
  '/api/ai-cs/v1/chat': typeof ApiAiCsV1ChatRoute
  '/api/ai-cs/v1/escalations': typeof ApiAiCsV1EscalationsRoute
  '/api/ai-cs/v1/sessions': typeof ApiAiCsV1SessionsRoute
  '/api/integrations/$provider/callback': typeof ApiIntegrationsProviderCallbackRoute
  '/api/marketing/lead-magnets/$slug': typeof ApiMarketingLeadMagnetsSlugRoute
  '/app/compliance/checklists/$checklistId': typeof AppComplianceChecklistsChecklistIdRoute
  '/app/compliance/incidents/$incidentId': typeof AppComplianceIncidentsIncidentIdRoute
  '/app/compliance/incidents/new': typeof AppComplianceIncidentsNewRoute
  '/app/compliance/program/risk': typeof AppComplianceProgramRiskRoute
  '/app/compliance/program/training': typeof AppComplianceProgramTrainingRoute
  '/app/compliance/program/vendors': typeof AppComplianceProgramVendorsRoute
  '/app/soc2/access-reviews/$reviewId': typeof AppSoc2AccessReviewsReviewIdRoute
  '/app/compliance/checklists': typeof AppComplianceChecklistsIndexRoute
  '/app/compliance/incidents': typeof AppComplianceIncidentsIndexRoute
  '/app/compliance/policies': typeof AppCompliancePoliciesIndexRoute
  '/app/compliance/program': typeof AppComplianceProgramIndexRoute
  '/app/soc2/access-reviews': typeof AppSoc2AccessReviewsIndexRoute
  '/app/compliance/program/policies/$policyId': typeof AppComplianceProgramPoliciesPolicyIdRoute
  '/app/compliance/program/policies': typeof AppComplianceProgramPoliciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/readyz': typeof ReadyzRoute
  '/signup': typeof SignupRouteWithChildren
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/help': typeof AppHelpRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/tasks': typeof AppTasksRouteWithChildren
  '/partner/$code': typeof PartnerCodeRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/verify': typeof PartnerVerifyRoute
  '/signup/check-email': typeof SignupCheckEmailRoute
  '/api/ai-cs/context': typeof ApiAiCsContextRoute
  '/api/analytics/product': typeof ApiAnalyticsProductRoute
  '/api/audit/export': typeof ApiAuditExportRoute
  '/api/marketing/leads': typeof ApiMarketingLeadsRoute
  '/api/marketing/promotion': typeof ApiMarketingPromotionRoute
  '/api/marketing/resend-webhook': typeof ApiMarketingResendWebhookRoute
  '/api/marketing/unsubscribe': typeof ApiMarketingUnsubscribeRoute
  '/api/partners/apply': typeof ApiPartnersApplyRoute
  '/api/soc2/bundles': typeof ApiSoc2BundlesRoute
  '/api/uploads/direct': typeof ApiUploadsDirectRoute
  '/api/uploads/mock': typeof ApiUploadsMockRoute
  '/api/uploads/scan-result': typeof ApiUploadsScanResultRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/app/admin/partners': typeof AppAdminPartnersRoute
  '/app/audit/export': typeof AppAuditExportRoute
  '/app/reports/compliance': typeof AppReportsComplianceRoute
  '/app/reports/tasks': typeof AppReportsTasksRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/locations': typeof AppSettingsLocationsRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security-keys': typeof AppSettingsSecurityKeysRoute
  '/app/soc2/access-reviews': typeof AppSoc2AccessReviewsRouteWithChildren
  '/app/soc2/auditor': typeof AppSoc2AuditorRoute
  '/app/soc2/controls': typeof AppSoc2ControlsRoute
  '/app/soc2/evidence': typeof AppSoc2EvidenceRoute
  '/app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/app/tasks/new': typeof AppTasksNewRoute
  '/app/audit/': typeof AppAuditIndexRoute
  '/app/compliance/': typeof AppComplianceIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/soc2/': typeof AppSoc2IndexRoute
  '/api/ai-cs/v1/chat': typeof ApiAiCsV1ChatRoute
  '/api/ai-cs/v1/escalations': typeof ApiAiCsV1EscalationsRoute
  '/api/ai-cs/v1/sessions': typeof ApiAiCsV1SessionsRoute
  '/api/integrations/$provider/callback': typeof ApiIntegrationsProviderCallbackRoute
  '/api/marketing/lead-magnets/$slug': typeof ApiMarketingLeadMagnetsSlugRoute
  '/app/compliance/checklists/$checklistId': typeof AppComplianceChecklistsChecklistIdRoute
  '/app/compliance/incidents/$incidentId': typeof AppComplianceIncidentsIncidentIdRoute
  '/app/compliance/incidents/new': typeof AppComplianceIncidentsNewRoute
  '/app/compliance/program/policies': typeof AppComplianceProgramPoliciesRouteWithChildren
  '/app/compliance/program/risk': typeof AppComplianceProgramRiskRoute
  '/app/compliance/program/training': typeof AppComplianceProgramTrainingRoute
  '/app/compliance/program/vendors': typeof AppComplianceProgramVendorsRoute
  '/app/soc2/access-reviews/$reviewId': typeof AppSoc2AccessReviewsReviewIdRoute
  '/app/compliance/checklists/': typeof AppComplianceChecklistsIndexRoute
  '/app/compliance/incidents/': typeof AppComplianceIncidentsIndexRoute
  '/app/compliance/policies/': typeof AppCompliancePoliciesIndexRoute
  '/app/compliance/program/': typeof AppComplianceProgramIndexRoute
  '/app/soc2/access-reviews/': typeof AppSoc2AccessReviewsIndexRoute
  '/app/compliance/program/policies/$policyId': typeof AppComplianceProgramPoliciesPolicyIdRoute
  '/app/compliance/program/policies/': typeof AppComplianceProgramPoliciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/health'
    | '/healthz'
    | '/login'
    | '/readyz'
    | '/signup'
    | '/accept-invite/$invitationId'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/help'
    | '/app/onboarding'
    | '/app/reports'
    | '/app/tasks'
    | '/partner/$code'
    | '/partner/dashboard'
    | '/partner/login'
    | '/partner/verify'
    | '/signup/check-email'
    | '/api/ai-cs/context'
    | '/api/analytics/product'
    | '/api/audit/export'
    | '/api/marketing/leads'
    | '/api/marketing/promotion'
    | '/api/marketing/resend-webhook'
    | '/api/marketing/unsubscribe'
    | '/api/partners/apply'
    | '/api/soc2/bundles'
    | '/api/uploads/direct'
    | '/api/uploads/mock'
    | '/api/uploads/scan-result'
    | '/api/webhooks/stripe'
    | '/app/admin/partners'
    | '/app/audit/export'
    | '/app/reports/compliance'
    | '/app/reports/tasks'
    | '/app/settings/integrations'
    | '/app/settings/locations'
    | '/app/settings/members'
    | '/app/settings/profile'
    | '/app/settings/security-keys'
    | '/app/soc2/access-reviews'
    | '/app/soc2/auditor'
    | '/app/soc2/controls'
    | '/app/soc2/evidence'
    | '/app/tasks/$taskId'
    | '/app/tasks/new'
    | '/app/audit/'
    | '/app/compliance/'
    | '/app/reports/'
    | '/app/settings/'
    | '/app/soc2/'
    | '/api/ai-cs/v1/chat'
    | '/api/ai-cs/v1/escalations'
    | '/api/ai-cs/v1/sessions'
    | '/api/integrations/$provider/callback'
    | '/api/marketing/lead-magnets/$slug'
    | '/app/compliance/checklists/$checklistId'
    | '/app/compliance/incidents/$incidentId'
    | '/app/compliance/incidents/new'
    | '/app/compliance/program/policies'
    | '/app/compliance/program/risk'
    | '/app/compliance/program/training'
    | '/app/compliance/program/vendors'
    | '/app/soc2/access-reviews/$reviewId'
    | '/app/compliance/checklists/'
    | '/app/compliance/incidents/'
    | '/app/compliance/policies/'
    | '/app/compliance/program/'
    | '/app/soc2/access-reviews/'
    | '/app/compliance/program/policies/$policyId'
    | '/app/compliance/program/policies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/health'
    | '/healthz'
    | '/login'
    | '/readyz'
    | '/signup'
    | '/accept-invite/$invitationId'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/help'
    | '/app/onboarding'
    | '/app/tasks'
    | '/partner/$code'
    | '/partner/dashboard'
    | '/partner/login'
    | '/partner/verify'
    | '/signup/check-email'
    | '/api/ai-cs/context'
    | '/api/analytics/product'
    | '/api/audit/export'
    | '/api/marketing/leads'
    | '/api/marketing/promotion'
    | '/api/marketing/resend-webhook'
    | '/api/marketing/unsubscribe'
    | '/api/partners/apply'
    | '/api/soc2/bundles'
    | '/api/uploads/direct'
    | '/api/uploads/mock'
    | '/api/uploads/scan-result'
    | '/api/webhooks/stripe'
    | '/app/admin/partners'
    | '/app/audit/export'
    | '/app/reports/compliance'
    | '/app/reports/tasks'
    | '/app/settings/integrations'
    | '/app/settings/locations'
    | '/app/settings/members'
    | '/app/settings/profile'
    | '/app/settings/security-keys'
    | '/app/soc2/auditor'
    | '/app/soc2/controls'
    | '/app/soc2/evidence'
    | '/app/tasks/$taskId'
    | '/app/tasks/new'
    | '/app/audit'
    | '/app/compliance'
    | '/app/reports'
    | '/app/settings'
    | '/app/soc2'
    | '/api/ai-cs/v1/chat'
    | '/api/ai-cs/v1/escalations'
    | '/api/ai-cs/v1/sessions'
    | '/api/integrations/$provider/callback'
    | '/api/marketing/lead-magnets/$slug'
    | '/app/compliance/checklists/$checklistId'
    | '/app/compliance/incidents/$incidentId'
    | '/app/compliance/incidents/new'
    | '/app/compliance/program/risk'
    | '/app/compliance/program/training'
    | '/app/compliance/program/vendors'
    | '/app/soc2/access-reviews/$reviewId'
    | '/app/compliance/checklists'
    | '/app/compliance/incidents'
    | '/app/compliance/policies'
    | '/app/compliance/program'
    | '/app/soc2/access-reviews'
    | '/app/compliance/program/policies/$policyId'
    | '/app/compliance/program/policies'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/health'
    | '/healthz'
    | '/login'
    | '/readyz'
    | '/signup'
    | '/accept-invite/$invitationId'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/help'
    | '/app/onboarding'
    | '/app/reports'
    | '/app/tasks'
    | '/partner/$code'
    | '/partner/dashboard'
    | '/partner/login'
    | '/partner/verify'
    | '/signup/check-email'
    | '/api/ai-cs/context'
    | '/api/analytics/product'
    | '/api/audit/export'
    | '/api/marketing/leads'
    | '/api/marketing/promotion'
    | '/api/marketing/resend-webhook'
    | '/api/marketing/unsubscribe'
    | '/api/partners/apply'
    | '/api/soc2/bundles'
    | '/api/uploads/direct'
    | '/api/uploads/mock'
    | '/api/uploads/scan-result'
    | '/api/webhooks/stripe'
    | '/app/admin/partners'
    | '/app/audit/export'
    | '/app/reports/compliance'
    | '/app/reports/tasks'
    | '/app/settings/integrations'
    | '/app/settings/locations'
    | '/app/settings/members'
    | '/app/settings/profile'
    | '/app/settings/security-keys'
    | '/app/soc2/access-reviews'
    | '/app/soc2/auditor'
    | '/app/soc2/controls'
    | '/app/soc2/evidence'
    | '/app/tasks/$taskId'
    | '/app/tasks/new'
    | '/app/audit/'
    | '/app/compliance/'
    | '/app/reports/'
    | '/app/settings/'
    | '/app/soc2/'
    | '/api/ai-cs/v1/chat'
    | '/api/ai-cs/v1/escalations'
    | '/api/ai-cs/v1/sessions'
    | '/api/integrations/$provider/callback'
    | '/api/marketing/lead-magnets/$slug'
    | '/app/compliance/checklists/$checklistId'
    | '/app/compliance/incidents/$incidentId'
    | '/app/compliance/incidents/new'
    | '/app/compliance/program/policies'
    | '/app/compliance/program/risk'
    | '/app/compliance/program/training'
    | '/app/compliance/program/vendors'
    | '/app/soc2/access-reviews/$reviewId'
    | '/app/compliance/checklists/'
    | '/app/compliance/incidents/'
    | '/app/compliance/policies/'
    | '/app/compliance/program/'
    | '/app/soc2/access-reviews/'
    | '/app/compliance/program/policies/$policyId'
    | '/app/compliance/program/policies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthRoute: typeof HealthRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  ReadyzRoute: typeof ReadyzRoute
  SignupRoute: typeof SignupRouteWithChildren
  AcceptInviteInvitationIdRoute: typeof AcceptInviteInvitationIdRoute
  PartnerCodeRoute: typeof PartnerCodeRoute
  PartnerDashboardRoute: typeof PartnerDashboardRoute
  PartnerLoginRoute: typeof PartnerLoginRoute
  PartnerVerifyRoute: typeof PartnerVerifyRoute
  ApiAiCsContextRoute: typeof ApiAiCsContextRoute
  ApiAnalyticsProductRoute: typeof ApiAnalyticsProductRoute
  ApiAuditExportRoute: typeof ApiAuditExportRoute
  ApiMarketingLeadsRoute: typeof ApiMarketingLeadsRoute
  ApiMarketingPromotionRoute: typeof ApiMarketingPromotionRoute
  ApiMarketingResendWebhookRoute: typeof ApiMarketingResendWebhookRoute
  ApiMarketingUnsubscribeRoute: typeof ApiMarketingUnsubscribeRoute
  ApiPartnersApplyRoute: typeof ApiPartnersApplyRoute
  ApiSoc2BundlesRoute: typeof ApiSoc2BundlesRoute
  ApiUploadsDirectRoute: typeof ApiUploadsDirectRoute
  ApiUploadsMockRoute: typeof ApiUploadsMockRoute
  ApiUploadsScanResultRoute: typeof ApiUploadsScanResultRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiAiCsV1ChatRoute: typeof ApiAiCsV1ChatRoute
  ApiAiCsV1EscalationsRoute: typeof ApiAiCsV1EscalationsRoute
  ApiAiCsV1SessionsRoute: typeof ApiAiCsV1SessionsRoute
  ApiIntegrationsProviderCallbackRoute: typeof ApiIntegrationsProviderCallbackRoute
  ApiMarketingLeadMagnetsSlugRoute: typeof ApiMarketingLeadMagnetsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite/$invitationId': {
      id: '/accept-invite/$invitationId'
      path: '/accept-invite/$invitationId'
      fullPath: '/accept-invite/$invitationId'
      preLoaderRoute: typeof AcceptInviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/partner/$code': {
      id: '/partner/$code'
      path: '/partner/$code'
      fullPath: '/partner/$code'
      preLoaderRoute: typeof PartnerCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/dashboard': {
      id: '/partner/dashboard'
      path: '/partner/dashboard'
      fullPath: '/partner/dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/login': {
      id: '/partner/login'
      path: '/partner/login'
      fullPath: '/partner/login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/verify': {
      id: '/partner/verify'
      path: '/partner/verify'
      fullPath: '/partner/verify'
      preLoaderRoute: typeof PartnerVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/check-email': {
      id: '/signup/check-email'
      path: '/check-email'
      fullPath: '/signup/check-email'
      preLoaderRoute: typeof SignupCheckEmailRouteImport
      parentRoute: typeof SignupRoute
    }
    '/api/ai-cs/context': {
      id: '/api/ai-cs/context'
      path: '/api/ai-cs/context'
      fullPath: '/api/ai-cs/context'
      preLoaderRoute: typeof ApiAiCsContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/product': {
      id: '/api/analytics/product'
      path: '/api/analytics/product'
      fullPath: '/api/analytics/product'
      preLoaderRoute: typeof ApiAnalyticsProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit/export': {
      id: '/api/audit/export'
      path: '/api/audit/export'
      fullPath: '/api/audit/export'
      preLoaderRoute: typeof ApiAuditExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing/leads': {
      id: '/api/marketing/leads'
      path: '/api/marketing/leads'
      fullPath: '/api/marketing/leads'
      preLoaderRoute: typeof ApiMarketingLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing/promotion': {
      id: '/api/marketing/promotion'
      path: '/api/marketing/promotion'
      fullPath: '/api/marketing/promotion'
      preLoaderRoute: typeof ApiMarketingPromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing/resend-webhook': {
      id: '/api/marketing/resend-webhook'
      path: '/api/marketing/resend-webhook'
      fullPath: '/api/marketing/resend-webhook'
      preLoaderRoute: typeof ApiMarketingResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing/unsubscribe': {
      id: '/api/marketing/unsubscribe'
      path: '/api/marketing/unsubscribe'
      fullPath: '/api/marketing/unsubscribe'
      preLoaderRoute: typeof ApiMarketingUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/partners/apply': {
      id: '/api/partners/apply'
      path: '/api/partners/apply'
      fullPath: '/api/partners/apply'
      preLoaderRoute: typeof ApiPartnersApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soc2/bundles': {
      id: '/api/soc2/bundles'
      path: '/api/soc2/bundles'
      fullPath: '/api/soc2/bundles'
      preLoaderRoute: typeof ApiSoc2BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/direct': {
      id: '/api/uploads/direct'
      path: '/api/uploads/direct'
      fullPath: '/api/uploads/direct'
      preLoaderRoute: typeof ApiUploadsDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/mock': {
      id: '/api/uploads/mock'
      path: '/api/uploads/mock'
      fullPath: '/api/uploads/mock'
      preLoaderRoute: typeof ApiUploadsMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/scan-result': {
      id: '/api/uploads/scan-result'
      path: '/api/uploads/scan-result'
      fullPath: '/api/uploads/scan-result'
      preLoaderRoute: typeof ApiUploadsScanResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/partners': {
      id: '/app/admin/partners'
      path: '/admin/partners'
      fullPath: '/app/admin/partners'
      preLoaderRoute: typeof AppAdminPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit/': {
      id: '/app/audit/'
      path: '/audit'
      fullPath: '/app/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit/export': {
      id: '/app/audit/export'
      path: '/audit/export'
      fullPath: '/app/audit/export'
      preLoaderRoute: typeof AppAuditExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/': {
      id: '/app/compliance/'
      path: '/compliance'
      fullPath: '/app/compliance/'
      preLoaderRoute: typeof AppComplianceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/compliance': {
      id: '/app/reports/compliance'
      path: '/compliance'
      fullPath: '/app/reports/compliance'
      preLoaderRoute: typeof AppReportsComplianceRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/tasks': {
      id: '/app/reports/tasks'
      path: '/tasks'
      fullPath: '/app/reports/tasks'
      preLoaderRoute: typeof AppReportsTasksRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/integrations': {
      id: '/app/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/app/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/locations': {
      id: '/app/settings/locations'
      path: '/settings/locations'
      fullPath: '/app/settings/locations'
      preLoaderRoute: typeof AppSettingsLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/members': {
      id: '/app/settings/members'
      path: '/settings/members'
      fullPath: '/app/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/settings/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/security-keys': {
      id: '/app/settings/security-keys'
      path: '/settings/security-keys'
      fullPath: '/app/settings/security-keys'
      preLoaderRoute: typeof AppSettingsSecurityKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/soc2/': {
      id: '/app/soc2/'
      path: '/soc2'
      fullPath: '/app/soc2/'
      preLoaderRoute: typeof AppSoc2IndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/soc2/access-reviews': {
      id: '/app/soc2/access-reviews'
      path: '/soc2/access-reviews'
      fullPath: '/app/soc2/access-reviews'
      preLoaderRoute: typeof AppSoc2AccessReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/soc2/auditor': {
      id: '/app/soc2/auditor'
      path: '/soc2/auditor'
      fullPath: '/app/soc2/auditor'
      preLoaderRoute: typeof AppSoc2AuditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/soc2/controls': {
      id: '/app/soc2/controls'
      path: '/soc2/controls'
      fullPath: '/app/soc2/controls'
      preLoaderRoute: typeof AppSoc2ControlsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/soc2/evidence': {
      id: '/app/soc2/evidence'
      path: '/soc2/evidence'
      fullPath: '/app/soc2/evidence'
      preLoaderRoute: typeof AppSoc2EvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks/$taskId': {
      id: '/app/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/app/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/app/tasks/new': {
      id: '/app/tasks/new'
      path: '/new'
      fullPath: '/app/tasks/new'
      preLoaderRoute: typeof AppTasksNewRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/api/ai-cs/v1/chat': {
      id: '/api/ai-cs/v1/chat'
      path: '/api/ai-cs/v1/chat'
      fullPath: '/api/ai-cs/v1/chat'
      preLoaderRoute: typeof ApiAiCsV1ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-cs/v1/escalations': {
      id: '/api/ai-cs/v1/escalations'
      path: '/api/ai-cs/v1/escalations'
      fullPath: '/api/ai-cs/v1/escalations'
      preLoaderRoute: typeof ApiAiCsV1EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-cs/v1/sessions': {
      id: '/api/ai-cs/v1/sessions'
      path: '/api/ai-cs/v1/sessions'
      fullPath: '/api/ai-cs/v1/sessions'
      preLoaderRoute: typeof ApiAiCsV1SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/$provider/callback': {
      id: '/api/integrations/$provider/callback'
      path: '/api/integrations/$provider/callback'
      fullPath: '/api/integrations/$provider/callback'
      preLoaderRoute: typeof ApiIntegrationsProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing/lead-magnets/$slug': {
      id: '/api/marketing/lead-magnets/$slug'
      path: '/api/marketing/lead-magnets/$slug'
      fullPath: '/api/marketing/lead-magnets/$slug'
      preLoaderRoute: typeof ApiMarketingLeadMagnetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/compliance/checklists/': {
      id: '/app/compliance/checklists/'
      path: '/compliance/checklists'
      fullPath: '/app/compliance/checklists/'
      preLoaderRoute: typeof AppComplianceChecklistsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/checklists/$checklistId': {
      id: '/app/compliance/checklists/$checklistId'
      path: '/compliance/checklists/$checklistId'
      fullPath: '/app/compliance/checklists/$checklistId'
      preLoaderRoute: typeof AppComplianceChecklistsChecklistIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/incidents/': {
      id: '/app/compliance/incidents/'
      path: '/compliance/incidents'
      fullPath: '/app/compliance/incidents/'
      preLoaderRoute: typeof AppComplianceIncidentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/incidents/$incidentId': {
      id: '/app/compliance/incidents/$incidentId'
      path: '/compliance/incidents/$incidentId'
      fullPath: '/app/compliance/incidents/$incidentId'
      preLoaderRoute: typeof AppComplianceIncidentsIncidentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/incidents/new': {
      id: '/app/compliance/incidents/new'
      path: '/compliance/incidents/new'
      fullPath: '/app/compliance/incidents/new'
      preLoaderRoute: typeof AppComplianceIncidentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/policies/': {
      id: '/app/compliance/policies/'
      path: '/compliance/policies'
      fullPath: '/app/compliance/policies/'
      preLoaderRoute: typeof AppCompliancePoliciesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/program/': {
      id: '/app/compliance/program/'
      path: '/compliance/program'
      fullPath: '/app/compliance/program/'
      preLoaderRoute: typeof AppComplianceProgramIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/program/policies': {
      id: '/app/compliance/program/policies'
      path: '/compliance/program/policies'
      fullPath: '/app/compliance/program/policies'
      preLoaderRoute: typeof AppComplianceProgramPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/program/risk': {
      id: '/app/compliance/program/risk'
      path: '/compliance/program/risk'
      fullPath: '/app/compliance/program/risk'
      preLoaderRoute: typeof AppComplianceProgramRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/program/training': {
      id: '/app/compliance/program/training'
      path: '/compliance/program/training'
      fullPath: '/app/compliance/program/training'
      preLoaderRoute: typeof AppComplianceProgramTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/program/vendors': {
      id: '/app/compliance/program/vendors'
      path: '/compliance/program/vendors'
      fullPath: '/app/compliance/program/vendors'
      preLoaderRoute: typeof AppComplianceProgramVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/soc2/access-reviews/': {
      id: '/app/soc2/access-reviews/'
      path: '/'
      fullPath: '/app/soc2/access-reviews/'
      preLoaderRoute: typeof AppSoc2AccessReviewsIndexRouteImport
      parentRoute: typeof AppSoc2AccessReviewsRoute
    }
    '/app/soc2/access-reviews/$reviewId': {
      id: '/app/soc2/access-reviews/$reviewId'
      path: '/$reviewId'
      fullPath: '/app/soc2/access-reviews/$reviewId'
      preLoaderRoute: typeof AppSoc2AccessReviewsReviewIdRouteImport
      parentRoute: typeof AppSoc2AccessReviewsRoute
    }
    '/app/compliance/program/policies/': {
      id: '/app/compliance/program/policies/'
      path: '/'
      fullPath: '/app/compliance/program/policies/'
      preLoaderRoute: typeof AppComplianceProgramPoliciesIndexRouteImport
      parentRoute: typeof AppComplianceProgramPoliciesRoute
    }
    '/app/compliance/program/policies/$policyId': {
      id: '/app/compliance/program/policies/$policyId'
      path: '/$policyId'
      fullPath: '/app/compliance/program/policies/$policyId'
      preLoaderRoute: typeof AppComplianceProgramPoliciesPolicyIdRouteImport
      parentRoute: typeof AppComplianceProgramPoliciesRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsComplianceRoute: typeof AppReportsComplianceRoute
  AppReportsTasksRoute: typeof AppReportsTasksRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsComplianceRoute: AppReportsComplianceRoute,
  AppReportsTasksRoute: AppReportsTasksRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppTasksRouteChildren {
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppTasksNewRoute: typeof AppTasksNewRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppTasksNewRoute: AppTasksNewRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppSoc2AccessReviewsRouteChildren {
  AppSoc2AccessReviewsReviewIdRoute: typeof AppSoc2AccessReviewsReviewIdRoute
  AppSoc2AccessReviewsIndexRoute: typeof AppSoc2AccessReviewsIndexRoute
}

const AppSoc2AccessReviewsRouteChildren: AppSoc2AccessReviewsRouteChildren = {
  AppSoc2AccessReviewsReviewIdRoute: AppSoc2AccessReviewsReviewIdRoute,
  AppSoc2AccessReviewsIndexRoute: AppSoc2AccessReviewsIndexRoute,
}

const AppSoc2AccessReviewsRouteWithChildren =
  AppSoc2AccessReviewsRoute._addFileChildren(AppSoc2AccessReviewsRouteChildren)

interface AppComplianceProgramPoliciesRouteChildren {
  AppComplianceProgramPoliciesPolicyIdRoute: typeof AppComplianceProgramPoliciesPolicyIdRoute
  AppComplianceProgramPoliciesIndexRoute: typeof AppComplianceProgramPoliciesIndexRoute
}

const AppComplianceProgramPoliciesRouteChildren: AppComplianceProgramPoliciesRouteChildren =
  {
    AppComplianceProgramPoliciesPolicyIdRoute:
      AppComplianceProgramPoliciesPolicyIdRoute,
    AppComplianceProgramPoliciesIndexRoute:
      AppComplianceProgramPoliciesIndexRoute,
  }

const AppComplianceProgramPoliciesRouteWithChildren =
  AppComplianceProgramPoliciesRoute._addFileChildren(
    AppComplianceProgramPoliciesRouteChildren,
  )

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpRoute: typeof AppHelpRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppAdminPartnersRoute: typeof AppAdminPartnersRoute
  AppAuditExportRoute: typeof AppAuditExportRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsLocationsRoute: typeof AppSettingsLocationsRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityKeysRoute: typeof AppSettingsSecurityKeysRoute
  AppSoc2AccessReviewsRoute: typeof AppSoc2AccessReviewsRouteWithChildren
  AppSoc2AuditorRoute: typeof AppSoc2AuditorRoute
  AppSoc2ControlsRoute: typeof AppSoc2ControlsRoute
  AppSoc2EvidenceRoute: typeof AppSoc2EvidenceRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
  AppComplianceIndexRoute: typeof AppComplianceIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSoc2IndexRoute: typeof AppSoc2IndexRoute
  AppComplianceChecklistsChecklistIdRoute: typeof AppComplianceChecklistsChecklistIdRoute
  AppComplianceIncidentsIncidentIdRoute: typeof AppComplianceIncidentsIncidentIdRoute
  AppComplianceIncidentsNewRoute: typeof AppComplianceIncidentsNewRoute
  AppComplianceProgramPoliciesRoute: typeof AppComplianceProgramPoliciesRouteWithChildren
  AppComplianceProgramRiskRoute: typeof AppComplianceProgramRiskRoute
  AppComplianceProgramTrainingRoute: typeof AppComplianceProgramTrainingRoute
  AppComplianceProgramVendorsRoute: typeof AppComplianceProgramVendorsRoute
  AppComplianceChecklistsIndexRoute: typeof AppComplianceChecklistsIndexRoute
  AppComplianceIncidentsIndexRoute: typeof AppComplianceIncidentsIndexRoute
  AppCompliancePoliciesIndexRoute: typeof AppCompliancePoliciesIndexRoute
  AppComplianceProgramIndexRoute: typeof AppComplianceProgramIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHelpRoute: AppHelpRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppAdminPartnersRoute: AppAdminPartnersRoute,
  AppAuditExportRoute: AppAuditExportRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsLocationsRoute: AppSettingsLocationsRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityKeysRoute: AppSettingsSecurityKeysRoute,
  AppSoc2AccessReviewsRoute: AppSoc2AccessReviewsRouteWithChildren,
  AppSoc2AuditorRoute: AppSoc2AuditorRoute,
  AppSoc2ControlsRoute: AppSoc2ControlsRoute,
  AppSoc2EvidenceRoute: AppSoc2EvidenceRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
  AppComplianceIndexRoute: AppComplianceIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSoc2IndexRoute: AppSoc2IndexRoute,
  AppComplianceChecklistsChecklistIdRoute:
    AppComplianceChecklistsChecklistIdRoute,
  AppComplianceIncidentsIncidentIdRoute: AppComplianceIncidentsIncidentIdRoute,
  AppComplianceIncidentsNewRoute: AppComplianceIncidentsNewRoute,
  AppComplianceProgramPoliciesRoute:
    AppComplianceProgramPoliciesRouteWithChildren,
  AppComplianceProgramRiskRoute: AppComplianceProgramRiskRoute,
  AppComplianceProgramTrainingRoute: AppComplianceProgramTrainingRoute,
  AppComplianceProgramVendorsRoute: AppComplianceProgramVendorsRoute,
  AppComplianceChecklistsIndexRoute: AppComplianceChecklistsIndexRoute,
  AppComplianceIncidentsIndexRoute: AppComplianceIncidentsIndexRoute,
  AppCompliancePoliciesIndexRoute: AppCompliancePoliciesIndexRoute,
  AppComplianceProgramIndexRoute: AppComplianceProgramIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SignupRouteChildren {
  SignupCheckEmailRoute: typeof SignupCheckEmailRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupCheckEmailRoute: SignupCheckEmailRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthRoute: HealthRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  ReadyzRoute: ReadyzRoute,
  SignupRoute: SignupRouteWithChildren,
  AcceptInviteInvitationIdRoute: AcceptInviteInvitationIdRoute,
  PartnerCodeRoute: PartnerCodeRoute,
  PartnerDashboardRoute: PartnerDashboardRoute,
  PartnerLoginRoute: PartnerLoginRoute,
  PartnerVerifyRoute: PartnerVerifyRoute,
  ApiAiCsContextRoute: ApiAiCsContextRoute,
  ApiAnalyticsProductRoute: ApiAnalyticsProductRoute,
  ApiAuditExportRoute: ApiAuditExportRoute,
  ApiMarketingLeadsRoute: ApiMarketingLeadsRoute,
  ApiMarketingPromotionRoute: ApiMarketingPromotionRoute,
  ApiMarketingResendWebhookRoute: ApiMarketingResendWebhookRoute,
  ApiMarketingUnsubscribeRoute: ApiMarketingUnsubscribeRoute,
  ApiPartnersApplyRoute: ApiPartnersApplyRoute,
  ApiSoc2BundlesRoute: ApiSoc2BundlesRoute,
  ApiUploadsDirectRoute: ApiUploadsDirectRoute,
  ApiUploadsMockRoute: ApiUploadsMockRoute,
  ApiUploadsScanResultRoute: ApiUploadsScanResultRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiAiCsV1ChatRoute: ApiAiCsV1ChatRoute,
  ApiAiCsV1EscalationsRoute: ApiAiCsV1EscalationsRoute,
  ApiAiCsV1SessionsRoute: ApiAiCsV1SessionsRoute,
  ApiIntegrationsProviderCallbackRoute: ApiIntegrationsProviderCallbackRoute,
  ApiMarketingLeadMagnetsSlugRoute: ApiMarketingLeadMagnetsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
