export { SUPPORT_EMAIL, SUPPORT_EMAIL_FROM, SUPPORT_EMAIL_MAILTO } from './contact.js'
export {
  PHIGUARD_APP_ORIGIN,
  PHIGUARD_EMAIL_FOOTER_ENTITY,
  PHIGUARD_EMAIL_LOGO_URL,
  PHIGUARD_LEGAL_ENTITY,
  PHIGUARD_NOTICE_ADDRESS_LINES,
  PHIGUARD_PRODUCT_NAME,
  PHIGUARD_PUBLIC_SITE_ORIGIN,
  PHIGUARD_SIGNUP_URL,
} from './identity.js'
export {
  PHIGUARD_EMAIL_PUBLIC_COPY,
  PHIGUARD_PARTNER_PROGRAM_COPY,
  PHIGUARD_PUBLIC_COMMERCIAL_COPY,
} from './public-copy.js'
