import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  schema: [
    './src/schema/auth.phi.ts',
    './src/schema/users.phi.ts',
    './src/schema/organizations.ts',
    './src/schema/locations.ts',
    './src/schema/location-grants.ts',
    './src/schema/memberships.ts',
    './src/schema/organization-invitations.phi.ts',
    './src/schema/tasks.phi.ts',
    './src/schema/task-assignments.phi.ts',
    './src/schema/task-comments.phi.ts',
    './src/schema/task-attachments.phi.ts',
    './src/schema/evidence-file-scans.phi.ts',
    './src/schema/legal-acceptances.phi.ts',
    './src/schema/partners.ts',
    './src/schema/referrals.ts',
    './src/schema/referral-revenue-events.ts',
    './src/schema/partner-payouts.ts',
    './src/schema/partner-users.ts',
    './src/schema/partner-magic-link-tokens.ts',
    './src/schema/integrations.phi.ts',
    './src/schema/policies.ts',
    './src/schema/policy-acknowledgements.phi.ts',
    './src/schema/training-courses.ts',
    './src/schema/training-records.phi.ts',
    './src/schema/risk-assessments.ts',
    './src/schema/vendors.ts',
    './src/schema/vendor-baas.phi.ts',
    './src/schema/soc2-controls.ts',
    './src/schema/soc2-evidence.ts',
    './src/schema/access-reviews.ts',
    './src/schema/rate-limit-buckets.ts',
    './src/schema/stripe-events.ts',
    './src/schema/webhook-events.ts',
    './src/schema/feature-usage.ts',
    './src/schema/ai-cs-escalations.phi.ts',
    './src/schema/ai-cs-nonces.ts',
    '../compliance/src/schema/checklist-templates.ts',
    '../compliance/src/schema/checklists.ts',
    '../compliance/src/schema/checklist-items.phi.ts',
    '../compliance/src/schema/policies.ts',
    '../compliance/src/schema/policy-assignments.ts',
    '../compliance/src/schema/incidents.phi.ts',
    '../compliance/src/schema/incident-updates.phi.ts',
  ],
  out: './drizzle',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL ?? '',
  },
})
