export {
  HELP_CATEGORIES,
  HELP_TOPICS,
  ROUTE_HELP,
  SUPPORT_EMAIL,
  SUPPORT_PHI_WARNING,
  appPublicGuidanceCopy,
  getHelpTopic,
  getHelpTopicsByCategory,
  getRouteHelp,
  searchHelpTopics,
  type HelpCategory,
  type HelpTopic,
  type HelpTopicLink,
  type HelpTooltipContent,
  type RouteHelpContent,
} from '@phiguard/knowledge/app'
