export {
  LEAD_CAPTURE_CTA_CONTEXTS,
  LEAD_MAGNETS,
  LEAD_MAGNETS_BY_SLUG,
  LEAD_MAGNET_TITLES,
  NEWSLETTER_SLUG,
  NEWSLETTER_TITLE,
  getDefaultPopupMagnetSlug,
  getLeadMagnetBySlug,
  getPopupPageCluster,
  getPopupPickerSlugs,
  isLeadCaptureCtaContext,
  isLeadCaptureSlug,
  isLeadMagnetSlug,
  isPopupExcludedPath,
  shouldSuppressPopup,
  type LeadCaptureCtaContext,
  type LeadCaptureSlug,
  type LeadMagnetDefinition,
  type LeadMagnetSlug,
  type PopupPageCluster,
} from '@phiguard/lead-magnets'
